import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const walsheim = localFont({
  src: [
    {
      path: "../public/font/subset-GTWalsheim-Bold.ttf", // Ruta absoluta desde la raíz pública
      weight: "700",
    },
    {
      path: "../public/font/subset-GTWalsheim-Medium.ttf",
      weight: "500",
    },
    {
      path: "../public/font/subset-GTWalsheim-Regular-_1.ttf",
      weight: "400",
    },
  ],
});

export const metadata: Metadata = {
  title: "Car Deals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={walsheim.className}>
      <body className={`${walsheim.className} ${walsheim.style} antialiased`}>
        {children}
      </body>
    </html>
  );
}
